<?php 
$pageTitle="FAQs";
$pageDesc="All the frequently asked questions about MyTeam."; 
include('inc/head.php'); ?>
<body>
  <?php 
include('inc/nav.php'); ?>
  <div class="w-container program-page">
    <div class="content page">
      <h2 class="page">Frequently asked questions</h2>
        <h4 class="program-page">
          What is MyTeam?
        </h4>
          <p class="program-page">
            MyTeam offers affordable programs to help you reach your health and fitness goals.
            <br>
            Your MyTeam coach will guide you through each step of your program. 
          </p>
        <h4 class="program-page">
          Who is behind MyTeam?
        </h4>
          <p class="program-page">
            MyTeam was started by John Sawers and Chris Baker. John worked at the largest social network for health in the UK, helping people with health problems get the support they need online. Chris is a designer, obsessed with the impact design can have on behavioural change. They share a passion for living healthy lives and a desire to reduce the cost of access to quality information and training support. Together they have assembled a team of top quality coaches and experts to deliver this service. 
          </p>
        <h4 class="program-page">
          What makes MyTeam better than other health &amp; fitness programs?
        </h4>
          <p class="program-page">
            In the age of apps, we believe in the value of a human connection. Each of our members gets a program tailored for their needs generated by a human trainer not a computer. You’ll be held accountable and get support from your coach, your community and yourself - working together to ensure you get results. 
          </p>
        <h4 class="program-page">
          How long does a program run for?
        </h4>
          <p class="program-page">
            A typical training program is designed to take around 2-4 months. 
          </p>
        <h4 class="program-page">
          What happens when my program finishes?
        </h4>
          <p class="program-page">
            If you haven’t completed your program by the time it is scheduled to finish you will be able to apply for access to your community and coach at a discounted rate giving you enough time to get there.
          </p>
        <h4 class="program-page">
          How much does it cost?
        </h4>
          <p class="program-page">
            A typical program costs £29 a month. This is less than the cost of a single face to face training session. 
          </p>
        <h4 class="program-page">
          What happens after I sign up?
        </h4>
          <p class="program-page">
            After you sign up you will receive an email from your coach asking you to complete a short assessment. Following this you will set a date for a telephone consultation to introduce you to your coach and set your goals together. Your coach will then create your custom program and send you all the details required to get started. 
          </p>
        <h4 class="program-page">
          Can I cancel my membership after I’ve started?
        </h4>
          <p class="program-page">
            You can cancel your membership at any time. If you do we will refund you for the remaining duration of your program. 
          </p>
        <h4 class="program-page">
          Who are the MyTeam coaches?
        </h4>
          <p class="program-page">
            MyTeam’s coaches are highly qualified specialists in the fields of weight loss, muscle gain, cardiovascular development and nutrition. In addition, we have a network of dieticians & sport scientists who work with us to ensure all our programs are of the highest standards.
          </p>
        <h4 class="program-page">
          Do I have to interact with the other members in my team?
        </h4>
          <p class="program-page">
            Members are encouraged to support and get to know the other members in their teams but it isn’t required. You contribute to the community as much or as little as you want. 
          </p>
        <h4 class="program-page" id="guarantee">
          How does your 100% guarantee work?
        </h4>
          <p class="program-page">
            If at any point during the first 45 days of your membership you are not completely satisfied with your experience just let us know and we will refund your program fee immediately. 
          </p>
    </div>
  </div>
  <?php 
include('inc/footer.php'); ?>
</body>
</html>